import pandas as pd, numpy as np
df=pd.read_csv('catA_results.csv')
TY={0:'S0',1:'Sa',2:'Sab',3:'Sb',4:'Sbc',5:'Sc',6:'Scd',7:'Sd',8:'Sdm',9:'Sm',10:'Im',11:'BCD'}
def gn(g): return g.replace('-','--')
N=len(df); g=df.grade.value_counts()
med=lambda c: np.median(df[c])
L=[]; A=L.append
A(r"""\documentclass[10pt]{article}
\usepackage[a4paper,margin=2cm]{geometry}
\usepackage{booktabs,longtable,amsmath,graphicx,pdfpages,caption,lscape}
\captionsetup{font=small,labelfont=bf}
\title{\bfseries Single-Lagrangian CL inflow fits of the SPARC category-A galaxies:\\ fit quality, parameter determination and robustness}
\author{Automated analysis for E.P.J.\ de Haas}\date{}
\begin{document}\maketitle
\section*{Summary}""")
A(f"""Of the 175 SPARC galaxies, {N} fall in category A after the single-Lagrangian (single-L) constant-Lagrangian (CL) inflow fit: their weighted residuals show no significant coherent structure (runs test $p\\ge0.05$) and $\\chi^2_\\nu\\le1$. For these galaxies the two-parameter CL curve is a statistically complete description of the SPARC rotation curve. The global $\\chi^2$ is {df.chi2.sum():.1f} for {int((df.n-2).sum())} degrees of freedom ($\\chi^2_\\nu={df.chi2.sum()/(df.n-2).sum():.3f}$), the median relative RMS residual in $v^2$ is {med('RMSrel'):.3f}, and no residual exceeds $2\\sigma$. The asymptotic CL speed $v_L=\\sqrt{{3/2}}\\,X$ is determined to a median {100*med('relV'):.1f}\\%, while $M$ and $R$ individually reach {100*med('relM'):.0f}\\% and {100*med('relR'):.0f}\\% because they are strongly correlated (median $\\rho_{{MR}}={med('rho_MR'):.3f}$). The fitted parameters track independent photometric quantities: $v_L$ versus SPARC $V_\\mathrm{{flat}}$ gives $r=0.994$, $\\log M$ versus $\\log M_\\mathrm{{bar}}$ gives $r=0.81$, and $R$ versus $R_\\mathrm{{disk}}$ gives Spearman $\\rho=0.68$. A three-level grading gives {g.get('I',0)} galaxies of grade I (both parameters robustly determined), {g.get('II',0)} of grade II (asymptotic speed determined, $M$ and $R$ partly degenerate) and {g.get('III',0)} of grade III (under-constrained). The main limitation is not the model but the data: category A is dominated by late-type dwarfs with few points (median $n={int(med('n'))}$), and the SPARC velocity errors are conservative relative to the scatter about the CL curve, so a good fit here is partly the absence of evidence against the model.""")
A(r"""
\section{Sample and selection}
Category A was defined in the pipeline run on all 175 SPARC galaxies (Lelli, McGaugh \& Schombert 2016): after the single-L fit, a galaxy is in A when the one-sided Wald--Wolfowitz runs test on the signs of the weighted residuals gives $p_\mathrm{runs}\ge0.05$ (no excess of long same-sign stretches), and $\chi^2_\nu\le1$. Galaxies with a $+-+$ wave (B), a $-+-$ wave (C), other significant structure (D), or $\chi^2_\nu>1$ without structure (E) are excluded.""")
A(f"""The selection has three consequences that must be kept in mind. (i) It favours late types: {int((df['T']>=8).sum())} of {N} are Sdm--BCD (median type {TY[int(med('T'))]}). (ii) It favours short rotation curves: median $n={int(med('n'))}$, only {int((df.n>=10).sum())} galaxies have $n\\ge10$, and {int((df.n_in<2).sum())} have fewer than two points inside the fitted $R$ ({int((df.n_in==0).sum())} have none). (iii) It includes all quality classes ({int((df.Q==1).sum())} Q=1, {int((df.Q==2).sum())} Q=2, {int((df.Q==3).sum())} Q=3). The runs test has low power for small $n$, so category A membership means \\emph{{no detectable}} structure, not proof that none exists.""")
A(r"""
\section{Model and methods}
\paragraph{Model.} The single-L CL inflow curve (de Haas, SPARC $H_z$ paper, Eqs.~17--18), with $X=\sqrt{2GM/R}-H_zR$:
\begin{equation*}
v^2(r)=\tfrac12X^2\,r^2/R^2\quad(r\le R),\qquad v^2(r)=\tfrac32X^2-\bigl(\sqrt{2GM/r}-H_zr\bigr)^2\quad(r>R),
\end{equation*}
with $H_z=2.2\times10^{-18}\,\mathrm{s^{-1}}$ fixed, and asymptotic speed $v_L=\sqrt{3/2}\,X$. The fit is to $v^2$ with $\sigma_{v^2}=2V_\mathrm{obs}\,\delta V_\mathrm{obs}$, by bounded least squares from 14 starting radii.
\paragraph{Uncertainties.} Statistical: $1\sigma$ from the local covariance $(J^\mathsf{T}J)^{-1}$; $\sigma_{v_L}$ by linear propagation including the $M$--$R$ covariance. Jackknife: leave-one-out refits, giving a jackknife error and the largest parameter shift in units of $\sigma$. Systematic: the data are refitted with the distance increased by $\delta D$ (radii scale with $D$) and with the inclination increased by $\delta i$ (velocities scale with $1/\sin i$, errors likewise); the two shifts are added in quadrature. SPARC velocity errors exclude both effects.
\paragraph{Fit-quality statistics.} $\chi^2$, $\chi^2_\nu$; the lower-tail probability $P(\chi^2\le\chi^2_\mathrm{obs})$ for $n-2$ degrees of freedom (small values signal overestimated errors); $\mathrm{RMS_{rel}}$ of $(v^2_\mathrm{obs}-v^2_\mathrm{mod})/v^2_\mathrm{obs}$; runs test $p_\mathrm{runs}$; Durbin--Watson statistic DW (2 for uncorrelated residuals); Shapiro--Wilk normality $p_\mathrm{SW}$; fraction of points within $1\sigma$; and $\Delta\mathrm{BIC}_\mathrm{off}$, the BIC change on adding a constant offset $V_0^2$ (2018 RMWRSS variant).
\paragraph{Robustness checks.} The fit is repeated with $H_z=0$ (the 2018 RMWRSS model) to measure the sensitivity to the cosmological term.
\paragraph{Grading.} \textbf{I}: $n\ge8$, at least 2 points inside and 3 outside $R$, $\sigma_M/M\le0.3$, $\sigma_R/R\le0.3$, and no jackknife shift above $2\sigma$. \textbf{II}: not I, but $\sigma_{v_L}/v_L\le0.10$. \textbf{III}: the rest. Galaxies with $P(\chi^2\le\chi^2_\mathrm{obs})<0.01$ are flagged as having conservative errors.
""")
A(r"\section{Global fit quality}")
A(r"\begin{table}[h]\centering\small\caption{Category-A fit-quality statistics (54 galaxies).}\begin{tabular}{lrrrr}\toprule Statistic & 16\% & median & 84\% & range\\\midrule")
for c,lab,d in [('n','$n$',0),('chi2nu','$\\chi^2_\\nu$',3),('p_chi2_low','$P(\\chi^2\\le\\chi^2_\\mathrm{obs})$',3),('RMSrel','RMS$_\\mathrm{rel}$',3),('p_runs','$p_\\mathrm{runs}$',3),
                ('DW','Durbin--Watson',2),('p_SW','$p_\\mathrm{SW}$',3),('frac1s','fraction $|\\mathrm{WR}|\\le1$',2),('maxabsz','max $|\\mathrm{WR}|$',2),('rho_MR','$\\rho_{MR}$',3),
                ('relM','$\\sigma_M/M$',3),('relR','$\\sigma_R/R$',3),('relV','$\\sigma_{v_L}/v_L$',3),('dBIC_offset','$\\Delta$BIC$_\\mathrm{off}$',2)]:
    q=np.percentile(df[c],[16,50,84]); A(f"{lab} & {q[0]:.{d}f} & {q[1]:.{d}f} & {q[2]:.{d}f} & {df[c].min():.{d}f}--{df[c].max():.{d}f}\\\\")
A(r"\bottomrule\end{tabular}\end{table}")
A(f"""\\paragraph{{Residual distribution.}} The {int(df.n.sum())} pooled weighted residuals (Fig.~1) are centred on zero and close to Gaussian in shape, but their dispersion is only {np.sqrt(df.chi2.sum()/df.n.sum()):.2f}, against 1 expected for correctly scaled errors. After rescaling each galaxy by $\\sqrt{{\\chi^2_\\nu}}$ the Q--Q plot is linear over $\\pm2.5\\sigma$. Shapiro--Wilk rejects normality ($p<0.05$) in only {int((df.p_SW<0.05).sum())} galaxies (CamB, F571-V1, UGC 11557), about the {0.05*N:.1f} expected by chance. No residual exceeds $2\\sigma$, and only one galaxy has fewer than 68\\% of its points within $1\\sigma$.

\\paragraph{{Error calibration.}} The lower-tail probability $P(\\chi^2\\le\\chi^2_\\mathrm{{obs}})$ is far from uniform (Fig.~1, right): {int((df.p_chi2_low<0.05).sum())} galaxies lie below 0.05 and {int(df.err_over.sum())} below 0.01. With only two free parameters this cannot be overfitting; it means that SPARC's $\\delta V_\\mathrm{{obs}}$, which by construction include kinematic asymmetries and non-circular motions, are on average about {np.sqrt(1/(df.chi2.sum()/(df.n-2).sum())):.1f} times larger than the scatter of the data about the CL curve. Two consequences follow: $\\chi^2_\\nu<1$ cannot be used to rank galaxies within category A, and the covariance uncertainties quoted below are conservative.

\\paragraph{{Residual structure.}} By selection $p_\\mathrm{{runs}}\\ge0.05$ throughout, but {int((df.p_runs<0.1).sum())} galaxies lie between 0.05 and 0.1 and {int((df.DW<1).sum())} have DW $<1$. These are the members closest to category B or C and the first candidates for a second Lagrangian if more data become available.

\\paragraph{{Offset and $H_z$.}} No galaxy requires the constant offset: the largest improvement is $\\Delta\\mathrm{{BIC_{{off}}}}=-3.1$ (UGC 6917), and the median is $+{med('dBIC_offset'):.1f}$, so the extra parameter is penalised. Setting $H_z=0$ changes $M$ by at most {100*np.max(np.abs(df.M_Hz0/df.M-1)):.1f}\\% and $R$ by at most {100*np.max(np.abs(df.R_Hz0/df.R-1)):.1f}\\%. At galactic scales the Hubble term is therefore negligible for the fit, and the 2018 RMWRSS ($H_z=0$) and present fits are equivalent for category A.
""")
A(r"\begin{figure}[h]\centering\includegraphics[width=\textwidth]{catA_fig_residuals.pdf}\caption{Left: pooled weighted residuals, raw (grey) and rescaled by $\sqrt{\chi^2_\nu}$ per galaxy (black), against N(0,1). Middle: Q--Q plot of the rescaled residuals. Right: distribution of $P(\chi^2\le\chi^2_\mathrm{obs})$; a uniform distribution (dashed) is expected if the SPARC errors were correctly scaled.}\end{figure}")
A(r"\section{Parameter determination}")
A(f"""The $M$--$R$ covariance dominates the parameter errors. The correlation coefficient ranges over {df.rho_MR.min():.3f}--{df.rho_MR.max():.3f}. The data constrain the combination $GM/R$, which sets the plateau $v_L^2\\simeq3GM/R$, much better than $M$ and $R$ separately, so solutions slide along lines of constant $v_L$ (Fig.~2, left). Accordingly $v_L$ is the best-determined quantity (median {100*med('relV'):.1f}\\%), followed by $R$ ({100*med('relR'):.0f}\\%) and $M$ ({100*med('relM'):.0f}\\%). $R$ is fixed mainly by where the inner parabola turns over into the outer branch. In the {int((df.n_in==0).sum())} galaxies with no point inside $R$, it is constrained only by the curvature of the outer branch $-2GM/r$, which works but is less precise.

The jackknife errors are smaller than the covariance errors (median ratio {np.median(df.jkM/df.eM):.2f} for $M$), consistent with the conservative SPARC errors. The largest single-point influence exceeds $2\\sigma$ in {int(((df.jk_shift_M>2)|(df.jk_shift_R>2)).sum())} galaxies. The systematic uncertainty from distance and inclination is comparable to the statistical one (median ratio {np.median(df.sysM/df.eM):.2f} for $M$ and {np.median(df.sysR/df.eR):.2f} for $R$), so it should always be quoted alongside it. It matters most for low-inclination galaxies, through the $1/\\sin^2 i$ scaling of $v^2$, and for Hubble-flow distances.""")
A(r"\begin{figure}[h]\centering\includegraphics[width=\textwidth]{catA_fig_params.pdf}\caption{Left: fitted $(R,M)$ with $1\sigma$ errors, coloured by grade; dotted lines are curves of constant $v_L$, along which the $M$--$R$ degeneracy runs. Middle: $M$--$R$ correlation versus number of points. Right: relative statistical uncertainties of $M$, $R$ and $v_L$.}\end{figure}")
A(r"\section{Physical consistency}")
okv=df.Vflat_obs>0
A(f"""For the {int(okv.sum())} galaxies with a SPARC $V_\\mathrm{{flat}}$, the CL asymptotic speed tracks it closely ($r=0.994$), with $v_L/V_\\mathrm{{flat}}$ = {np.median(df.vflat_CL[okv]/df.Vflat_obs[okv]):.3f} (median). The roughly 10\\% excess is expected rather than a bias: at the last measured radius the CL curve has reached only {np.median(df.vrmax_over_vL):.2f} of $v_L$ (median), whereas $V_\\mathrm{{flat}}$ is measured from the outermost points. The CL curve therefore predicts a continued slow rise of a few per cent beyond the data, which is a testable prediction for deeper H\\,\\textsc{{i}} observations. The fitted mass correlates with the SPARC baryonic mass ($M_\\mathrm{{bar}}=0.5L_\\mathrm{{disk}}+0.7L_\\mathrm{{bulge}}+1.33M_\\mathrm{{HI}}$; $r=0.81$ in log), with median $M/M_\\mathrm{{bar}}={np.median(df.M/df.Mbar):.2f}$ (16--84\\%: {np.percentile(df.M/df.Mbar,16):.2f}--{np.percentile(df.M/df.Mbar,84):.2f}). This is much tighter than the $r\\approx0.28$ found for the full 175-galaxy sample, and consistent with reading $M$ as the inner (bulge-like) mass rather than the total baryonic mass. $R$ is of the order of the disk scale length (median $R/R_\\mathrm{{disk}}={np.median(df.R/df.Rdisk):.2f}$, Spearman $\\rho=0.68$).""")
A(r"\begin{figure}[h]\centering\includegraphics[width=\textwidth]{catA_fig_physics.pdf}\caption{Left to right: CL $v_L$ versus SPARC $V_\mathrm{flat}$; $R$ versus $R_\mathrm{disk}$; $M$ versus $M_\mathrm{bar}$ (dashed: one-to-one); systematic (distance, inclination) versus statistical relative uncertainty of $M$ and $R$.}\end{figure}")
A(r"\section{Grades and assessment}")
A(f"""\\begin{{table}}[h]\\centering\\small\\caption{{Grades (medians per grade).}}\\begin{{tabular}}{{lrrrrrrr}}\\toprule Grade & $N$ & $n$ & $\\chi^2_\\nu$ & RMS$_\\mathrm{{rel}}$ & $\\sigma_M/M$ & $\\sigma_R/R$ & $\\sigma_{{v_L}}/v_L$\\\\\\midrule""")
for gr in ['I','II','III']:
    s=df[df.grade==gr]; A(f"{gr} & {len(s)} & {int(s.n.median())} & {s.chi2nu.median():.3f} & {s.RMSrel.median():.3f} & {s.relM.median():.3f} & {s.relR.median():.3f} & {s.relV.median():.3f}\\\\")
A(r"\bottomrule\end{tabular}\end{table}")
A(f"""\\textbf{{Grade I}} ({g.get('I',0)} galaxies, of which {int(((df.grade=='I')&(df.Q==1)).sum())} are Q=1) is the core result. The rotation curve samples both the inner parabola and the outer branch, both parameters are determined to better than 30\\%, and no single point drives the fit. These are clean, quantitative confirmations that a single constant Lagrangian describes the full rotation curve.
\\textbf{{Grade II}} ({g.get('II',0)}) fits as well statistically, but the data constrain mainly $v_L$. $M$ and $R$ are partly degenerate, usually because of few inner points. These galaxies support the model's plateau and shape but give weaker individual scale parameters.
\\textbf{{Grade III}} ({g.get('III',0)}) are consistent with the model but not informative: with $n\\le$ {int(df[df.grade=='III'].n.max())} points and parameter errors up to {100*df[df.grade=='III'].relM.max():.0f}\\%, almost any smooth rising curve would fit.

\\paragraph{{Overall assessment.}} Within category A the single-L CL model is statistically sufficient. It has no significant residual structure, Gaussian-shaped residuals, no outliers, no need for an offset, and parameters that agree with independent photometric and kinematic scales. Two limitations are intrinsic to the data rather than to the model. First, the SPARC errors are conservative, so goodness of fit cannot discriminate among the A galaxies or between the CL model and other two-parameter models on $\\chi^2$ alone. Second, short curves and the $M$--$R$ degeneracy mean that only about a third of the sample (grade I) determines both CL parameters robustly. For comparisons with MOND or dark-matter halos, the grade-I subset with total (statistical plus systematic) uncertainties is the appropriate sample.
""")
# ---- tables
A(r"\clearpage\begin{landscape}{\scriptsize\setlength{\tabcolsep}{3.5pt}")
A(r"""\begin{longtable}{llrrrrlllllrc}
\caption{Category-A parameters. $R$ in kpc, $M$ in $10^9M_\odot$, $v_L$ in km\,s$^{-1}$. Uncertainties: statistical (covariance) $\pm$ systematic (distance and inclination); jk = jackknife error. $n_\mathrm{in}/n_\mathrm{out}$ = points inside/outside $R$.}\\\toprule
Galaxy & Type & Q & $i$ & $n$ & $n_\mathrm{in}/n_\mathrm{out}$ & $R\pm$stat$\pm$sys & $M\pm$stat$\pm$sys & jk($R$, $M$) & $v_L$ & $\rho_{MR}$ & $V_\mathrm{flat}$ & Grade\\\midrule\endfirsthead
\toprule Galaxy & Type & Q & $i$ & $n$ & $n_\mathrm{in}/n_\mathrm{out}$ & $R\pm$stat$\pm$sys & $M\pm$stat$\pm$sys & jk($R$, $M$) & $v_L$ & $\rho_{MR}$ & $V_\mathrm{flat}$ & Grade\\\midrule\endhead\bottomrule\endfoot""")
for _,r in df.sort_values(['grade','Galaxy']).iterrows():
    vf='--' if r.Vflat_obs==0 else f"{r.Vflat_obs:.1f}"
    A(f"{gn(r.Galaxy)} & {TY[int(r['T'])]} & {int(r.Q)} & {r.Inc:.0f} & {int(r.n)} & {int(r.n_in)}/{int(r.n_out)} & ${r.R:.3f}\\pm{r.eR:.3f}\\pm{r.sysR:.3f}$ & ${r.M:.3g}\\pm{r.eM:.2g}\\pm{r.sysM:.2g}$ & {r.jkR:.2g}, {r.jkM:.2g} & ${r.vflat_CL:.1f}\\pm{r.e_vflat_CL:.1f}$ & {r.rho_MR:.3f} & {vf} & {r.grade}\\\\")
A(r"\end{longtable}")
A(r"""\begin{longtable}{lrrrrrrrrrrrrc}
\caption{Category-A goodness of fit. $P_<=P(\chi^2\le\chi^2_\mathrm{obs})$; DW = Durbin--Watson; $f_{1\sigma}$ = fraction of points with $|\mathrm{WR}|\le1$; jk$_\mathrm{max}$ = largest leave-one-out shift of $M$ or $R$ in $\sigma$; $\Delta$BIC$_\mathrm{off}$ for an added constant offset; c = conservative-error flag ($P_<<0.01$).}\\\toprule
Galaxy & $n$ & $\chi^2$ & $\chi^2_\nu$ & $P_<$ & AIC & BIC & RMS$_\mathrm{rel}$ & $p_\mathrm{runs}$ & DW & $p_\mathrm{SW}$ & $f_{1\sigma}$ & jk$_\mathrm{max}$ & $\Delta$BIC$_\mathrm{off}$ / flag\\\midrule\endfirsthead
\toprule Galaxy & $n$ & $\chi^2$ & $\chi^2_\nu$ & $P_<$ & AIC & BIC & RMS$_\mathrm{rel}$ & $p_\mathrm{runs}$ & DW & $p_\mathrm{SW}$ & $f_{1\sigma}$ & jk$_\mathrm{max}$ & $\Delta$BIC$_\mathrm{off}$ / flag\\\midrule\endhead\bottomrule\endfoot""")
for _,r in df.sort_values(['grade','Galaxy']).iterrows():
    A(f"{gn(r.Galaxy)} & {int(r.n)} & {r.chi2:.2f} & {r.chi2nu:.3f} & {r.p_chi2_low:.3f} & {r.AIC:.2f} & {r.BIC:.2f} & {r.RMSrel:.3f} & {r.p_runs:.3f} & {r.DW:.2f} & {r.p_SW:.3f} & {r.frac1s:.2f} & {max(r.jk_shift_M,r.jk_shift_R):.2f} & {r.dBIC_offset:+.2f} {'c' if r.err_over else ''}\\\\")
A(r"\end{longtable}}\end{landscape}")
A(r"\section*{Atlas: category-A single-L fits with $1\sigma$ parameter band and weighted residuals}\includepdf[pages=-,landscape=true,scale=0.95]{catA_atlas.pdf}")
A(r"\end{document}")
open('CL_categoryA_report.tex','w').write('\n'.join(L))
